name: Deploy to Firebase Hosting on PR
on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci && npm run build

      # 👇 Renombrar index si existe (soporta index.csr.html o index.ssr.html)
      - run: |
          if [ -f dist/motorx-front/browser/index.csr.html ]; then
            mv dist/motorx-front/browser/index.csr.html dist/motorx-front/browser/index.html
          elif [ -f dist/motorx-front/browser/index.ssr.html ]; then
            mv dist/motorx-front/browser/index.ssr.html dist/motorx-front/browser/index.html
          elif [ -f dist/motorx-front/browser/index.html ]; then
            echo "index.html ya existe"
          else
            echo "No se encontró ningún index en dist/motorx-front/browser" >&2
            ls -la dist/motorx-front/browser || true
            exit 1
          fi

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOTORX_CF34D }}
          projectId: motorx-cf34d